pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 6.0.x SDK'
  inputs:
    packageType: sdk
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Creating NuGet package (with debug symbols)'
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    includesymbols: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: 'Pushing NuGet package'
  condition: and(succeeded(), not(eq(variables['Build.Reason'], 'PullRequest')))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.snupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'
