pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 8.0.x SDK'
  inputs:
    packageType: sdk
    version: '8.0.x'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.12.2'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: 'Creating NuGet package (with debug symbols)'
  inputs:
    command: 'custom'
    projects: '**/Revit.SDK.20*.csproj'
    custom: 'msbuild'
    arguments: '/t:Pack'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: NuGetCommand@2
  displayName: 'Pushing NuGet package'
  inputs:
    command: 'push'
    allowPackageConflicts: true
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.snupkg;!$(Build.SourcesDirectory)/**/*.snupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'AzureNuget'

